### ISSUE TITLE
Create simple app to test Espresso

### ISSUE THREAD

**Issue by nathanchen13** [TranslationWMcs435/TranslationWMcs435#12]
I can't get the source code for the GM Dice to work since the source code doesn't include the gradle it needs to run in Android Studio. So I am going to make a simple app so that I can ensure that the output from the Espresso part of the Translation Engine works.

**Comment by MarkHutchens** [comment]
Have you finished the simple app?

**Comment by nathanchen13** [comment]
This might have to be moved to sprint 2. I've been trying to get Android Studio to work with Espresso for the last couple hours and I can't find what's wrong.

**Comment by MarkHutchens** [comment]
Mostly, I hope you went to sleep at some point. We need to divvy up the work better for the next sprint.
