### ISSUE TITLE
Parse swipes for Espresso

### ISSUE THREAD

**Issue by nathanchen13** [TranslationWMcs435/TranslationWMcs435#16]
Swipe inputs need to be able to taken in as input from JSON files and translated to their Espresso functions.

**Comment by nathanchen13** [comment]
Not for Sprint 2. I was mistaken, type is what was wanted for sprint 2.

**Comment by MarkHutchens** [comment]
Ergo, reassign to Sprint 3.

**Comment by nathanchen13** [comment]
Need the specs on how swipes are represented in the JSON File. Will move this issue to the next sprint since it is not urgent.

**Comment by nathanchen13** [comment]
I opened issue #46, it encompasses this issue so I am closing this issue.
