### ISSUE TITLE
Add Option Functionality for Appium (Output options)

### ISSUE THREAD

**Issue by nathanchen13** [TranslationWMcs435/TranslationWMcs435#19]
For Appium, needs to be able to output a java class file and be able to run the input on the given app as the JSON file is being translated to Appium. The user gets to choose which one they want.

**Comment by MarkHutchens** [comment]
You have the class file at least. Was there luck on getting a live feed going?

**Comment by King-AK** [comment]
I have a live version going for Appium that works by just passing it
TestCase tc from Main.java.
