### ISSUE TITLE
Add more inputs for Espresso

### ISSUE THREAD

**Issue by nathanchen13** [TranslationWMcs435/TranslationWMcs435#46]
Add more input types, ask Carlos for the ones he wants. I will comment with a list of the inputs he wants.

**Comment by nathanchen13** [comment]
Specifically need to add swiping and scrolling (some frameworks autoscroll I believe, so add scroll for those who do not have this feature).

**Comment by MarkHutchens** [comment]
I'd like to take one of these two from you, so you don't have a hellish workload (and so I feel more useful).

**Comment by nathanchen13** [comment]
I have added up, down, left, and right swipes.
