### ISSUE TITLE
UiAutomator launch app before testing

### ISSUE THREAD

**Issue by nathanchen13** [TranslationWMcs435/TranslationWMcs435#47]
Add functionality so that the app is open before the tests are performed.

**Comment by nathanchen13** [comment]
This seems to be more difficult than I though. I am still working on finding a solution.

**Comment by nathanchen13** [comment]
Moving to sprint 5 for now, there may not be a way to launch the app from the home screen on any type of Android device. It seems you can write code for specific Android versions, but it is different for each version and then also different for each kind of Android phone (ie. HTC, Samsung, other Android phones with their own UI overlays, etc).

**Comment by MarkHutchens** [comment]
I make no claim of universality, but I've gotten it to work on a Nexus 5 emulator, assuming that we can get the JSON  to show the app name AS IT APPEARS ON THE APP SCREEN.

Still need to automate the code generation, but that shouldn't be too hard to fake. It's only 13 lines to go home, push the app button, and then do a loop as you try to click on an app with the right name.
