### ISSUE TITLE
Parse long clicks for Espresso

### ISSUE THREAD

**Issue by MarkHutchens** [TranslationWMcs435/TranslationWMcs435#6]
Long taps, swipes, etc. are a lower priority than taps for this sprint, but if we have time, we can try for them.

**Comment by MarkHutchens** [comment]
With Sprint 2, we need to get other forms of input working for both espresso and appium. Priority goes up to high.

**Comment by nathanchen13** [comment]
Long tap capability has been added. Espresso translator can now parse long click actions from the JSON file and translate it into Espresso functions.
