### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by nathanchen13** [TranslationWMcs435/TranslationWMcs435#61]
For some reason removing the package name from the JSON file will cause a bunch of NullPointerExceptions to pop up in places where they shouldn't be. Tested on EspressoTranslator. Figure out why this is happening.

**Comment by MarkHutchens** [comment]
Did this one ever get fixed, or should I take a quick look at it?

EDIT: Removing the package name now causes the JSON file to be rejected by the Espresso Checker. I'm gonna assume you forgot to mark this resolved, but let you do it anyway.
