### ISSUE TITLE
Add assert statements for test cases for Robotium

### ISSUE THREAD

**Issue by tranindigo** [TranslationWMcs435/TranslationWMcs435#65]
So far, we have written action statements into TestFile.java or some other output file, and our test cases will **always** pass. However, remember that test cases should also contain assert statements to make sure that our tests will not only pass, but can also fail as well. 

Something like: assertThat(results.getText().toString(), equalTo("Testing Android Rocks!"));

We should do this for every framework.

**Comment by tranindigo** [comment]
Also, we should discuss fail criteria.

**Comment by tranindigo** [comment]
That is, when should we fail the test case? Under what circumstances? When should our test case automatically fail?

**Comment by MarkHutchens** [comment]
Carlos doesn't really want this feature, so we are removing it.
