### ISSUE TITLE
Create Storage class for input items in JSON file

### ISSUE THREAD

**Issue by nathanchen13** [TranslationWMcs435/TranslationWMcs435#8]
I have discovered that using GSON we can parse items in the JSON file into Java objects, so we need a storage class. I can work on this because I know what it needs.

**Comment by MarkHutchens** [comment]
Sounds good. Could you check out my skeleton I committed last night? I have no idea if it is usable on another machine yet.

**Comment by nathanchen13** [comment]
Yep I'll do that now.

**Comment by tranindigo** [comment]
Your skeleton works on Eclipse on my machine (I have Windows).

**Comment by nathanchen13** [comment]
I can also verify it works on Windows

**Comment by nathanchen13** [comment]
This issue was completed by Mark. He used the source code in the Classes folder to this end.
