### ISSUE TITLE
Unit Tests for Checker

### ISSUE THREAD

**Issue by MarkHutchens** [TranslationWMcs435/TranslationWMcs435#93]

**Comment by tranindigo** [comment]
Check

**Comment by MarkHutchens** [comment]
K guys, everyone look through the slides so we can divvy up talking time. VJ, check your part of slide 7, I added stuff based on your commits, but you may be able to expand it more.

We got this.

~Mark

**Comment by tranindigo** [comment]
Assign me something plz
